### ISSUE TITLE
[Suggestion] Detect Application Start-up

### ISSUE THREAD

**Issue by KianaR** [shizus/compromiso-estudio#6]
Potentially a good idea to try detect if/when the assigned .exe file has started-up, and then run the application accordingly. 

@shizus let me know what you think 👍

**Comment by shizus** [comment]
Hi @KianaR I think that would have some performance issues and could be very invasive for some users.
The main use for this project right now is to replace a direct access to a game in desktop to prevent opening a game when you have other obligations to comply first. So I think the next step for the project would be to add screen in the app that help no developer users to setup their settings.json.

It could be a simple window with a file selector that only let you select direct accesses in your desktop, once you selected it, it requests a are-you-sure question and a commitment phrase and when you click "replace direct access" it deletes your direct access and replace it with the one that calls this program before opening the real game.

Does it make sense?

**Comment by KianaR** [comment]
Hey @shizus !

This makes total sense to me, I think I must have misunderstood what the aim of this project was originally. I agree that the concept could be quite invasive, so allowing a user-controlled block would be a friendly approach for sure. 

Should we create an issue for creating a screen for modifying the settings.json and close this question?

**Comment by shizus** [comment]
that would be great! 😃
